export enum MetodoPagoDetalle {
  EFECTIVO_USD = 'EFECTIVO_USD',
  EFECTIVO_BSD = 'EFECTIVO_BSD',
  ZELLE = 'ZELLE',
  PAGO_MOVIL = 'PAGO_MOVIL',
  TRANSFERENCIA = 'TRANSFERENCIA',
  PUNTO_VENTA = 'PUNTO_VENTA',
  BINANCE = 'BINANCE'
}